Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,12 +61,44 @@ jobs:
            EOF
            echo "✅ Backup created at /home/ec2-user/BACKUP_NEW.sql inside AWS server"
 
+
+
+      - name: Verify Backup File Exists
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ec2-user@13.212.238.210 \
+          'if [ -f /home/ec2-user/BACKUP_NEW.sql ]; then 
+             echo "✅ Backup file found!";
+              ls -l /home/ec2-user/BACKUP_NEW.sql
+           else 
+             echo "❌ Backup file NOT found!"; exit 1;
+           fi'
+
+           
+
       - name: Run Liquibase UPDATE with Properties File
         run: |
           echo " Running Liquibase update..."
           /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties update --changelog-file=liquibase/changelog.xml --log-level=debug
-        #continue-on-error: true  # Prevents pipeline from failing immediately
+        continue-on-error: true  # Prevents pipeline from failing immediately
 
+
+      - name: Rollback If Update Fails (Drop and Recreate Database)
+        if: failure()
+        run: |
+          echo "❌ Liquibase update failed! Restoring database from backup..."
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ec2-user@13.212.238.210 << 'EOF'
+            mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "DROP DATABASE IF EXISTS database2;"
+            mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE database2;"
+          EOF
+          echo "✅ Database dropped and recreated successfully!"
+
+
+
+      - name: Restore Database from Backup
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ec2-user@13.212.238.210 \
+          'mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" database2 < /home/ec2-user/BACKUP_NEW.sql'
+          echo "✅ Database rollback completed successfully!"
 
 
       - name: Print Success Message
