Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,11 @@ jobs:
         run: |
           nc -zv 13.212.238.210 3306
 
+      - name: Debug Liquibase Properties
+        run: |
+          ls -l liquibase/
+          cat liquibase/liquibase.properties || echo "⚠️ liquibase.properties NOT FOUND!"
+
 
       - name: Run Liquibase STATUS with Properties File
         run: |
