Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,9 @@
-name: Liquibase Migration
+name: Liquibase Migrationn
 
 on:
   push:
     branches:
-      - main
+      - main # Change this if needed
     paths:
       - '/opt/liquibase/changelog.xml'
   
@@ -17,25 +17,30 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-
       - name: Set Up Liquibase
         run: |
           wget https://github.com/liquibase/liquibase/releases/download/v4.25.0/liquibase-4.25.0.zip
           unzip liquibase-4.25.0.zip -d /opt/liquibase
           chmod +x /opt/liquibase/liquibase
 
-          
+
       - name: Test DB Connection
         run: |
           nc -zv 13.212.238.210 3306
 
-          
+
       - name: Copy Liquibase Configuration Files
         run: |
           mkdir -p /opt/liquibase  
-          cp $GITHUB_WORKSPACE/liquibase/liquibase.properties /opt/liquibase/liquibase.properties
-          cp $GITHUB_WORKSPACE/liquibase/changelog.xml /opt/liquibase/changelog.xml
+          cp $GITHUB_WORKSPACE/opt/liquibase/liquibase.properties /opt/liquibase/liquibase.properties
+          cp $GITHUB_WORKSPACE/opt/liquibase/changelog.xml /opt/liquibase/changelog.xml
           ls -l /opt/liquibase  
+
+
+      - name: Debug Liquibase Properties
+        run: |
+          ls -l /opt/liquibase/
+          cat /opt/liquibase/liquibase.properties || echo "⚠️ liquibase.properties NOT FOUND!"
 
 
       - name: Run Liquibase STATUS
